// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAn4dNU3ez3AIkiX64JUCegRL9gaOh2G7A',
    appId: '1:306927069503:web:181ce3a1bbfdc58d778b8a',
    messagingSenderId: '306927069503',
    projectId: 'help-hands-453ca',
    authDomain: 'help-hands-453ca.firebaseapp.com',
    storageBucket: 'help-hands-453ca.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB8jh4ITiEpM207TkemRpbbeeAj6ywXOew',
    appId: '1:306927069503:android:cc0e7f74e523a0e0778b8a',
    messagingSenderId: '306927069503',
    projectId: 'help-hands-453ca',
    storageBucket: 'help-hands-453ca.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCSeSb2sc8-BD7hctNpKWptUnVCJMK6cAM',
    appId: '1:306927069503:ios:98ce1f0249dfe5c5778b8a',
    messagingSenderId: '306927069503',
    projectId: 'help-hands-453ca',
    storageBucket: 'help-hands-453ca.appspot.com',
    iosClientId: '306927069503-qak8j72k9uhlkhi8gdj376o0koee3784.apps.googleusercontent.com',
    iosBundleId: 'com.example.sonsu',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCSeSb2sc8-BD7hctNpKWptUnVCJMK6cAM',
    appId: '1:306927069503:ios:98ce1f0249dfe5c5778b8a',
    messagingSenderId: '306927069503',
    projectId: 'help-hands-453ca',
    storageBucket: 'help-hands-453ca.appspot.com',
    iosClientId: '306927069503-qak8j72k9uhlkhi8gdj376o0koee3784.apps.googleusercontent.com',
    iosBundleId: 'com.example.sonsu',
  );
}
